sonar.projectKey=bioinspired-knapsack
sonar.host.url=http://localhost:9000
sonar.login=sqp_9a8727ca8fa095e1abaf868fb6254bb28906048b
sonar.sources=src,main.py
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml